# Web Scapping

Volveremos a repasar la ultima parte del archivo EDA para realizar nuevamente el web scrapping pero esta vez dejar la base de datos correctamente guardada y limpia.

In [1]:
import pandas as pd
import numpy as np
import requests
from io import BytesIO

%load_ext autoreload
%autoreload 2

import warnings
warnings.filterwarnings("ignore")

In [2]:
url = 'https://www.estadisticaciudad.gob.ar/eyc/wp-content/uploads/2025/05/PBP_CO_1020.xls'
ruta_archivo = 'Datasets/Evolucion_poblacion_CABA.xls'

response = requests.get(url)

if response.status_code == 200:
    excel_content = BytesIO(response.content)

    # Leer el archivo Excel
    df = pd.read_excel(excel_content)

    # Ahora 'df' contiene los datos del archivo Excel
    print(df.head())

else:
    print(f'Error al realizar la solicitud. Código de estado: {response.status_code}')

  Proyecciones de población por comuna y sexo. Ciudad de Buenos Aires. Años 2010/2025  \
0                                        Ambos sexos
1                                             Comuna
2                                              Total
3                                                  1
4                                                  2

   Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1      2010.0      2011.0      2012.0      2013.0      2014.0      2015.0
2   3028481.0   3033639.0   3038860.0   3044076.0   3049229.0   3054267.0
3    243946.0    245308.0    246689.0    248069.0    249433.0    250770.0
4    150714.0    150573.0    150428.0    150278.0    150130.0    149985.0

   Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  \
0         NaN         NaN         NaN          NaN          NaN          NaN
1      2016.0      2017.0      2018.0       2019.0       2020.0       2021.0
2   3059122.0   3063728.0   3068043.0    3072029.0    3075646.0    3078836.0
3    252053.0    253271.0    254408.0     255457.0     256405.0     257235.0
4    149848.0    149720.0    149607.0     149510.0     149430.0     149371.0

   Unnamed: 13  Unnamed: 14  Unnamed: 15 Unnamed: 16
0          NaN          NaN          NaN         NaN
1       2022.0       2023.0       2024.0        2025
2    3081550.0    3083770.0    3085483.0     3086680
3     257934.0     258497.0     258922.0      259205
4     149337.0     149328.0     149345.0      149389

In [3]:
df #vemos que hay mucha informacion de mas

,Proyecciones de población por comuna y sexo. Ciudad de Buenos Aires. Años 2010/2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Ambos sexos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Comuna,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025
2,Total,3028481.0,3033639.0,3038860.0,3044076.0,3049229.0,3054267.0,3059122.0,3063728.0,3068043.0,3072029.0,3075646.0,3078836.0,3081550.0,3083770.0,3085483.0,3086680
3,1,243946.0,245308.0,246689.0,248069.0,249433.0,250770.0,252053.0,253271.0,254408.0,255457.0,256405.0,257235.0,257934.0,258497.0,258922.0,259205
4,2,150714.0,150573.0,150428.0,150278.0,150130.0,149985.0,149848.0,149720.0,149607.0,149510.0,149430.0,149371.0,149337.0,149328.0,149345.0,149389
5,3,191323.0,191536.0,191750.0,191963.0,192171.0,192375.0,192573.0,192763.0,192945.0,193115.0,193276.0,193425.0,193560.0,193682.0,193790.0,193884
6,4,234933.0,235497.0,236071.0,236646.0,237214.0,237769.0,238303.0,238809.0,239279.0,239712.0,240100.0,240437.0,240716.0,240937.0,241096.0,241193
7,5,185301.0,185544.0,185789.0,186034.0,186276.0,186512.0,186740.0,186956.0,187159.0,187348.0,187518.0,187670.0,187800.0,187907.0,187991.0,188053
8,6,183046.0,183309.0,183576.0,183843.0,184105.0,184363.0,184611.0,184846.0,185067.0,185271.0,185456.0,185620.0,185760.0,185875.0,185964.0,186028
9,7,236838.0,237389.0,237946.0,238505.0,239057.0,239597.0,240116.0,240607.0,241065.0,241484.0,241861.0,242188.0,242460.0,242674.0,242828.0,242921
10,8,219638.0,220655.0,221693.0,222733.0,223764.0,224770.0,225737.0,226649.0,227495.0,228266.0,228953.0,229541.0,230018.0,230380.0,230623.0,230745
11,9,168681.0,168964.0,169248.0,169533.0,169814.0,170087.0,170353.0,170605.0,170842.0,171062.0,171264.0,171444.0,171600.0,171733.0,171839.0,171921
12,10,169372.0,169506.0,169640.0,169775.0,169908.0,170037.0,170163.0,170282.0,170394.0,170497.0,170592.0,170677.0,170750.0,170811.0,170859.0,170896
13,11,189760.0,189795.0,189829.0,189861.0,189893.0,189925.0,189956.0,189986.0,190016.0,190046.0,190076.0,190105.0,190135.0,190165.0,190195.0,190225
14,12,211320.0,211699.0,212082.0,212467.0,212846.0,213218.0,213576.0,213914.0,214229.0,214518.0,214777.0,215002.0,215189.0,215335.0,215442.0,215505
15,13,234846.0,235011.0,235178.0,235342.0,235506.0,235666.0,235819.0,235967.0,236107.0,236238.0,236358.0,236468.0,236566.0,236650.0,236723.0,236781
16,14,226489.0,226558.0,226626.0,226692.0,226758.0,226821.0,226884.0,226944.0,227003.0,227060.0,227115.0,227168.0,227219.0,227268.0,227315.0,227360
17,15,182274.0,182295.0,182315.0,182335.0,182354.0,182372.0,182390.0,182409.0,182427.0,182445.0,182465.0,182485.0,182506.0,182528.0,182551.0,182574
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(continúa)
19,Varón,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Comuna,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025
21,Total,1405566.0,1409835.0,1414105.0,1418339.0,1422507.0,1426582.0,1430531.0,1434323.0,1437936.0,1441350.0,1444545.0,1447495.0,1450179.0,1452588.0,1454716.0,1456560
22,1,117622.0,118720.0,119819.0,120907.0,121979.0,123030.0,124045.0,125021.0,125950.0,126828.0,127651.0,128410.0,129100.0,129720.0,130266.0,130742
23,2,67160.0,67110.0,67061.0,67011.0,66963.0,66915.0,66870.0,66825.0,66783.0,66744.0,66707.0,66672.0,66641.0,66613.0,66588.0,66567
24,3,89373.0,89585.0,89797.0,90008.0,90215.0,90417.0,90614.0,90802.0,90982.0,91151.0,91310.0,91457.0,91590.0,91710.0,91816.0,91907
25,4,110956.0,111394.0,111832.0,112267.0,112695.0,113113.0,113518.0,113908.0,114278.0,114629.0,114957.0,115260.0,115535.0,115782.0,116001.0,116190
26,5,84443.0,84648.0,84853.0,85056.0,85256.0,85451.0,85640.0,85822.0,85995.0,86159.0,86312.0,86453.0,86582.0,86697.0,86799.0,86888
27,6,82781.0,83001.0,83221.0,83440.0,83654.0,83865.0,84068.0,84263.0,84450.0,84626.0,84790.0,84942.0,85081.0,85205.0,85315.0,85410
28,7,110040.0,110466.0,110891.0,111313.0,111728.0,112134.0,112527.0,112905.0,113265.0,113605.0,113923.0,114217.0,114485.0,114725.0,114937.0,115120
29,8,102829.0,103576.0,104324.0,105065.0,105795.0,106508.0,107199.0,107863.0,108496.0,109093.0,109653.0,110169.0,110639.0,111061.0,111433.0,111756
30,9,80600.0,80847.0,81094.0,81339.0,81581.0,81816.0,82045.0,82265.0,82474.0,82671.0,82856.0,83027.0,83182.0,83322.0,83445.0,83552
31,10,79016.0,79131.0,79245.0,79360.0,79472.0,79581.0,79688.0,79790.0,79887.0,79979.0,80065.0,80145.0,80217.0,80282.0,80339.0,80389
32,11,89319.0,89367.0,89415.0,89462.0,89509.0,89555.0,89599.0,89641.0,89682.0,89720.0,89756.0,89789.0,89819.0,89846.0,89870.0,89891
33,12,97723.0,98016.0,98308.0,98598.0,98883.0,99162.0,99433.0,99692.0,99940.0,100174.0,100392.0,100594.0,100778.0,100943.0,101089.0,101215
34,13,106580.0,106734.0,106889.0,107042.0,107193.0,107341.0,107484.0,107621.0,107752.0,107876.0,107991.0,108098.0,108195.0,108282.0,108360.0,108426
35,14,102036.0,102118.0,102200.0,102281.0,102361.0,102439.0,102515.0,102588.0,102657.0,102723.0,102784.0,102841.0,102892.0,102938.0,102979.0,103014
36,15,85088.0,85122.0,85156.0,85190.0,85223.0,85255.0,85286.0,85317.0,85345.0,85372.0,85398.0,85421.0,85443.0,85462.0,85479.0,85493
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(continúa)
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Mujer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Comuna,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025
41,Total,1622915.0,1623804.0,1624755.0,1625737.0,1626722.0,1627685.0,1628591.0,1629405.0,1630107.0,1630679.0,1631101.0,1631341.0,1631371.0,1631182.0,1630767.0,1630120
42,1,126324.0,126588.0,126870.0,127162.0,127454.0,127740.0,128008.0,128250.0,128458.0,128629.0,128754.0,128825.0,128834.0,128777.0,128656.0,128463
43,2,83554.0,83463.0,83367.0,83267.0,83167.0,83070.0,82978.0,82895.0,82824.0,82766.0,82723.0,82699.0,82696.0,82715.0,82757.0,82822
44,3,101950.0,101951.0,101953.0,101955.0,101956.0,101958.0,101959.0,101961.0,101963.0,101964.0,101966.0,101968.0,101970.0,101972.0,101974.0,101977
45,4,123977.0,124103.0,124239.0,124379.0,124519.0,124656.0,124785.0,124901.0,125001.0,125083.0,125143.0,125177.0,125181.0,125155.0,125095.0,125003
46,5,100858.0,100896.0,100936.0,100978.0,101020.0,101061.0,101100.0,101134.0,101164.0,101189.0,101206.0,101217.0,101218.0,101210.0,101192.0,101165
47,6,100265.0,100308.0,100355.0,100403.0,100451.0,100498.0,100543.0,100583.0,100617.0,100645.0,100666.0,100678.0,100679.0,100670.0,100649.0,100618
48,7,126798.0,126923.0,127055.0,127192.0,127329.0,127463.0,127589.0,127702.0,127800.0,127879.0,127938.0,127971.0,127975.0,127949.0,127891.0,127801
49,8,116809.0,117079.0,117369.0,117668.0,117969.0,118262.0,118538.0,118786.0,118999.0,119173.0,119300.0,119372.0,119379.0,119319.0,119190.0,118989
50,9,88081.0,88117.0,88154.0,88194.0,88233.0,88271.0,88308.0,88340.0,88368.0,88391.0,88408.0,88417.0,88418.0,88411.0,88394.0,88369
51,10,90356.0,90375.0,90395.0,90415.0,90436.0,90456.0,90475.0,90492.0,90507.0,90518.0,90527.0,90532.0,90533.0,90529.0,90520.0,90507
52,11,100441.0,100428.0,100414.0,100399.0,100384.0,100370.0,100357.0,100345.0,100334.0,100326.0,100320.0,100316.0,100316.0,100319.0,100325.0,100334
53,12,113597.0,113683.0,113774.0,113869.0,113963.0,114056.0,114143.0,114222.0,114289.0,114344.0,114385.0,114408.0,114411.0,114392.0,114353.0,114290
54,13,128266.0,128277.0,128289.0,128300.0,128313.0,128325.0,128335.0,128346.0,128355.0,128362.0,128367.0,128370.0,128371.0,128368.0,128363.0,128355
55,14,124453.0,124440.0,124426.0,124411.0,124397.0,124382.0,124369.0,124356.0,124346.0,124337.0,124331.0,124327.0,124327.0,124330.0,124336.0,124346
56,15,97186.0,97173.0,97159.0,97145.0,97131.0,97117.0,97104.0,97092.0,97082.0,97073.0,97067.0,97064.0,97063.0,97066.0,97072.0,97081
57,Fuente: Dirección General de Estadística y Cen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
columnas = ['Comuna']
for i in range(2010,2026):
    columnas.append(i)
 # definimos nombre de columnas
columnas

['Comuna',
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 2025]

In [5]:
df.columns= columnas
df = df.iloc[3:18].reset_index(drop=True)
df #quedemonos con lo que nos interesa, ambos sexos

,Comuna,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,1,243946.0,245308.0,246689.0,248069.0,249433.0,250770.0,252053.0,253271.0,254408.0,255457.0,256405.0,257235.0,257934.0,258497.0,258922.0,259205
1,2,150714.0,150573.0,150428.0,150278.0,150130.0,149985.0,149848.0,149720.0,149607.0,149510.0,149430.0,149371.0,149337.0,149328.0,149345.0,149389
2,3,191323.0,191536.0,191750.0,191963.0,192171.0,192375.0,192573.0,192763.0,192945.0,193115.0,193276.0,193425.0,193560.0,193682.0,193790.0,193884
3,4,234933.0,235497.0,236071.0,236646.0,237214.0,237769.0,238303.0,238809.0,239279.0,239712.0,240100.0,240437.0,240716.0,240937.0,241096.0,241193
4,5,185301.0,185544.0,185789.0,186034.0,186276.0,186512.0,186740.0,186956.0,187159.0,187348.0,187518.0,187670.0,187800.0,187907.0,187991.0,188053
5,6,183046.0,183309.0,183576.0,183843.0,184105.0,184363.0,184611.0,184846.0,185067.0,185271.0,185456.0,185620.0,185760.0,185875.0,185964.0,186028
6,7,236838.0,237389.0,237946.0,238505.0,239057.0,239597.0,240116.0,240607.0,241065.0,241484.0,241861.0,242188.0,242460.0,242674.0,242828.0,242921
7,8,219638.0,220655.0,221693.0,222733.0,223764.0,224770.0,225737.0,226649.0,227495.0,228266.0,228953.0,229541.0,230018.0,230380.0,230623.0,230745
8,9,168681.0,168964.0,169248.0,169533.0,169814.0,170087.0,170353.0,170605.0,170842.0,171062.0,171264.0,171444.0,171600.0,171733.0,171839.0,171921
9,10,169372.0,169506.0,169640.0,169775.0,169908.0,170037.0,170163.0,170282.0,170394.0,170497.0,170592.0,170677.0,170750.0,170811.0,170859.0,170896
10,11,189760.0,189795.0,189829.0,189861.0,189893.0,189925.0,189956.0,189986.0,190016.0,190046.0,190076.0,190105.0,190135.0,190165.0,190195.0,190225
11,12,211320.0,211699.0,212082.0,212467.0,212846.0,213218.0,213576.0,213914.0,214229.0,214518.0,214777.0,215002.0,215189.0,215335.0,215442.0,215505
12,13,234846.0,235011.0,235178.0,235342.0,235506.0,235666.0,235819.0,235967.0,236107.0,236238.0,236358.0,236468.0,236566.0,236650.0,236723.0,236781
13,14,226489.0,226558.0,226626.0,226692.0,226758.0,226821.0,226884.0,226944.0,227003.0,227060.0,227115.0,227168.0,227219.0,227268.0,227315.0,227360
14,15,182274.0,182295.0,182315.0,182335.0,182354.0,182372.0,182390.0,182409.0,182427.0,182445.0,182465.0,182485.0,182506.0,182528.0,182551.0,182574

In [6]:
df.drop(columns=[2010,2011,2012,2013,2014,2015,2022,2023,2024,2025],inplace=True) #elijamos las columnas
df

   Comuna      2016      2017      2018      2019      2020      2021
0       1  252053.0  253271.0  254408.0  255457.0  256405.0  257235.0
1       2  149848.0  149720.0  149607.0  149510.0  149430.0  149371.0
2       3  192573.0  192763.0  192945.0  193115.0  193276.0  193425.0
3       4  238303.0  238809.0  239279.0  239712.0  240100.0  240437.0
4       5  186740.0  186956.0  187159.0  187348.0  187518.0  187670.0
5       6  184611.0  184846.0  185067.0  185271.0  185456.0  185620.0
6       7  240116.0  240607.0  241065.0  241484.0  241861.0  242188.0
7       8  225737.0  226649.0  227495.0  228266.0  228953.0  229541.0
8       9  170353.0  170605.0  170842.0  171062.0  171264.0  171444.0
9      10  170163.0  170282.0  170394.0  170497.0  170592.0  170677.0
10     11  189956.0  189986.0  190016.0  190046.0  190076.0  190105.0
11     12  213576.0  213914.0  214229.0  214518.0  214777.0  215002.0
12     13  235819.0  235967.0  236107.0  236238.0  236358.0  236468.0
13     14  226884.0  226944.0  227003.0  227060.0  227115.0  227168.0
14     15  182390.0  182409.0  182427.0  182445.0  182465.0  182485.0

Bueno, estas son las proyecciones realizadas por la ciudad de buenos aires y a los efectos de nuestro analisis las vamos a tomar como validas, mas alla de que pueden discurrir de la realidad exacta.

In [22]:
# pasemos este analisis a un formato de base de datos:

df_melted = pd.melt(df, id_vars=['Comuna'], var_name='Anio', value_name='Habitantes')

df_melted_total_anio = df_melted.groupby('Anio', as_index=False)['Habitantes'].sum()
df_melted_total_anio
df_melted_con_totales = pd.concat([df_melted, df_melted_total_anio]).reset_index(drop=True)
df_melted_con_totales

   Comuna  Anio  Habitantes
0       1  2016    252053.0
1       2  2016    149848.0
2       3  2016    192573.0
3       4  2016    238303.0
4       5  2016    186740.0
..    ...   ...         ...
91    NaN  2017   3063728.0
92    NaN  2018   3068043.0
93    NaN  2019   3072029.0
94    NaN  2020   3075646.0
95    NaN  2021   3078836.0

[96 rows x 3 columns]

No necesito por comuna.... ya que voy a tratar el KPI por totales y no separado.

In [17]:
df_melted_total_anio.to_csv('Datasets/Evolucion_poblacion_caba.csv',index=False)